// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 ImHoks <imhokzzzz@gmail.com>
// SPDX-FileCopyrightText: 2025 KillanGenifer <killangenifer@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.Graphics; // Dumont-Boris-Tags
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._CorvaxNext.Silicons.Borgs.Components;

namespace Content.Client._CorvaxNext.Silicons.Laws.Ui;

[GenerateTypedNameReferences]
public sealed partial class RemoteDeviceDisplay : Control
{
    public event Action<RemoteDeviceActionEvent>? OnRemoteDeviceAction;

    public RemoteDeviceDisplay(NetEntity netEntityUid, RemoteDevicesData device) // Dumont-Boris-Tags: recebe o registro inteiro
    {
        RobustXamlLoader.Load(this);

        var displayName = device.DisplayName;
        var isOccupied = device.IsOccupied; // Gabystation - ai fix

        DeviceName.SetMessage(displayName);

        // Dumont-Boris-Tags start: tag de função. com rádio é texto colorido igual ao chat,
        // sem rádio é texto normal com fundo cinza
        if (device.TagText != string.Empty)
        {
            TagPanel.Visible = true;

            if (device.TagIsRadio)
            {
                TagLabel.Text = $"[{device.TagText}]";
                TagLabel.FontColorOverride = device.TagColor;
            }
            else
            {
                TagLabel.Text = device.TagText;
                TagPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#4A4A52") };
            }
        }
        // Dumont-Boris-Tags end

        MoveButton.OnPressed += _ =>
        {
            OnRemoteDeviceAction?.Invoke(new RemoteDeviceActionEvent(
                RemoteDeviceActionEvent.RemoteDeviceActionType.MoveToDevice,
                netEntityUid));
        };

        TakeControlButton.Disabled = isOccupied; // Gabystation - ai fix
        TakeControlButton.OnPressed += _ =>
        {
            OnRemoteDeviceAction?.Invoke(new RemoteDeviceActionEvent(
                RemoteDeviceActionEvent.RemoteDeviceActionType.TakeControl,
                netEntityUid));
        };
    }
}
