// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Dumont.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Dumont.Silicons.StationAi.Ui;

[GenerateTypedNameReferences]
public sealed partial class AiAlertsMenu : FancyWindow
{
    private static readonly Color DangerColor = Color.FromHex("#ff4b4b");
    private static readonly Color WarningColor = Color.FromHex("#ffa500");
    private static readonly Color InfoColor = Color.FromHex("#5ed7aa");

    public event Action<NetEntity>? OnWarpTo;
    public event Action<NetEntity>? OnDismiss;

    public AiAlertsMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(AiAlertsBuiState state)
    {
        AlertsContainer.Children.Clear();

        if (state.Alerts.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("ai-alerts-ui-all-clear");
            return;
        }

        StatusLabel.Text = Loc.GetString("ai-alerts-ui-count", ("count", state.Alerts.Count));

        foreach (var alert in state.Alerts)
        {
            AlertsContainer.AddChild(BuildRow(alert));
        }
    }

    /// <summary>
    /// cada alerta vira um card: título colorido em cima, descrição embaixo quebrando
    /// linha, e o botão de ir com tamanho fixo na direita
    /// </summary>
    private Control BuildRow(AiAlertEntry alert)
    {
        var color = alert.Severity switch
        {
            AiAlertSeverity.Danger => DangerColor,
            AiAlertSeverity.Warning => WarningColor,
            _ => InfoColor,
        };

        string title;
        string desc;

        switch (alert.Kind)
        {
            case AiAlertKind.Waypoint:
                title = Loc.GetString("ai-alerts-ui-row-title-waypoint", ("color", color.ToHex()));
                desc = Loc.GetString("ai-alerts-ui-row-desc-waypoint", ("area", alert.Area));
                break;
            case AiAlertKind.Door:
                title = Loc.GetString("ai-alerts-ui-row-title-door", ("color", color.ToHex()));
                desc = Loc.GetString("ai-alerts-ui-row-desc-door", ("who", alert.Subject), ("area", alert.Area));
                break;
            default:
                var kind = Loc.GetString(alert.Kind == AiAlertKind.Fire
                    ? "station-ai-alarm-kind-fire"
                    : "station-ai-alarm-kind-atmos");
                var severity = Loc.GetString(alert.Severity == AiAlertSeverity.Danger
                    ? "ai-alerts-ui-severity-danger"
                    : "ai-alerts-ui-severity-warning");

                title = Loc.GetString("ai-alerts-ui-row-title-alarm",
                    ("color", color.ToHex()),
                    ("severity", severity),
                    ("kind", kind));
                desc = Loc.GetString("ai-alerts-ui-row-desc-alarm", ("area", alert.Area));
                break;
        }

        var titleLabel = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        titleLabel.SetMessage(FormattedMessage.FromMarkupPermissive(title));

        var descLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 0),
        };
        descLabel.SetMessage(FormattedMessage.FromMarkupPermissive(desc));

        // botões embaixo do texto, nunca do lado.. do lado o texto medía largura errada
        // e o botão desenhava por cima do parágrafo
        var target = alert.Source;

        var jump = new Button
        {
            Text = Loc.GetString("ai-alerts-ui-jump"),
            MinSize = new Vector2(72, 32),
        };
        jump.OnPressed += _ => OnWarpTo?.Invoke(target);

        var dismiss = new Button
        {
            Text = Loc.GetString(alert.Kind == AiAlertKind.Waypoint
                ? "ai-alerts-ui-remove"
                : "ai-alerts-ui-dismiss"),
            MinSize = new Vector2(72, 32),
            Margin = new Thickness(6, 0, 0, 0),
            Modulate = Color.FromHex("#b0b0b0"),
        };
        dismiss.OnPressed += _ => OnDismiss?.Invoke(target);

        var buttons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = Control.HAlignment.Right,
            Margin = new Thickness(0, 6, 0, 0),
        };
        buttons.AddChild(jump);
        buttons.AddChild(dismiss);

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(10, 8, 10, 8),
        };
        content.AddChild(titleLabel);
        content.AddChild(descLabel);
        content.AddChild(buttons);

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
        };
        panel.AddStyleClass("BackgroundDark");
        panel.AddChild(content);

        return panel;
    }
}
