// SPDX-FileCopyrightText: 2026 Project Dumont
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Resources;
using Content.Goobstation.Maths.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Xenobiology;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyConsoleStatusControl : Control
{
    [Dependency] private IResourceCache _resources = default!;

    public XenobiologyConsoleStatusControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var counterFont = _resources.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 10);
        BiomassLabel.FontOverride = counterFont;
        SlimeLabel.FontOverride = counterFont;
    }

    public void UpdateState(int storedSlimes, int maxStoredSlimes, FixedPoint2 monkeyBiomass)
    {
        BiomassLabel.Text = monkeyBiomass.ToString();
        SlimeLabel.Text = $"{storedSlimes}/{maxStoredSlimes}";
    }
}
