// SPDX-License-Identifier: AGPL-3.0-or-later

global using System.Numerics;
global using Robust.Client.AutoGenerated;
global using Robust.Client.GameObjects;
global using Robust.Client.Graphics;
global using Robust.Client.UserInterface;
global using Robust.Client.UserInterface.Controls;
global using Robust.Client.UserInterface.XAML;
global using Robust.Shared.GameStates;
global using Robust.Shared.Network;
global using Robust.Shared.Prototypes;
global using Robust.Shared.Serialization;
global using Robust.Shared.Utility;
