// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.WhiteDream.BloodCult.Commune;

[GenerateTypedNameReferences]
public sealed partial class BloodCultCommuneWindow : FancyWindow
{
    public Action<string>? OnCommune;

    public BloodCultCommuneWindow()
    {
        RobustXamlLoader.Load(this);

        CommuneMessageSend.OnPressed += _ => OnCommune?.Invoke(CommuneMessage.Text);
        CommuneMessage.OnTextEntered += _ => OnCommune?.Invoke(CommuneMessage.Text);
    }

    protected override void Opened()
    {
        base.Opened();

        // Focus the box so the cultist can just start typing.
        CommuneMessage.GrabKeyboardFocus();
    }

    public void UpdateState(string message)
    {
        CommuneMessage.Text = message;
    }
}
